### ISSUE TITLE
Turn off moleule resizing for search results

### ISSUE THREAD

**Issue by dslambrecht** [pittquantum/PittQuantumRepository#24]
Scrolling up/down the list of search results can cause excessive zoom in/out for the molecules. Resizing/zooming should be switched off in the search results list.

**Comment by JoshuaRogan** [comment]
Okay, I need to make the switch to all JavaScript generations before I can easily do this.

**Comment by ghutchis** [comment]
I think this is better addressed through #64.

**Comment by JoshuaRogan** [comment]
Fixed with #64
