### ISSUE TITLE
Add More Feedback Messages

### ISSUE THREAD

**Issue by JoshuaRogan** [pittquantum/PittQuantumRepository#34]
Add more responses such as when you increase font size, add a small message indicating that the font size has increased. Same for stopping rotation, removing surface, hiding information, etc.

**Comment by RitwikGupta** [comment]
http://codeseven.github.io/toastr/

**Comment by RitwikGupta** [comment]
@JoshuaRogan You can try this as well: http://goodybag.github.io/bootstrap-notify/

**Comment by JoshuaRogan** [comment]
I think that is what I will go with.
