### ISSUE TITLE
List of Molecules of the Week

### ISSUE THREAD

**Issue by ghutchis** [pittquantum/PittQuantumRepository#41]
There should be a way to pull up *previous* (i.e. old) molecules of the week.

**Comment by ghutchis** [comment]
These can be generated from the file (i.e., find all dates before the current date)

Date | Name
------------ | -------------
2015-06-01 | [Caffeine](http://pqr.pitt.edu/mol/RYYVLZVUVIJVGH-UHFFFAOYSA-N/)
2015-07-01 | [Fluorescein](http://pqr.pitt.edu/mol/GNBHRKFJIUUOQI-UHFFFAOYSA-N/)

**Comment by RitwikGupta** [comment]
Made it an API call

**Comment by ghutchis** [comment]
No, I really want a human-accessible page like "click on the Molecules of the Week" to get the table. API is fine, but it's important to have a route like pqr.pitt.edu/motw/

**Comment by RitwikGupta** [comment]
Makes sense. Will work on this with @JoshuaRogan

**Comment by ghutchis** [comment]
What's the status on this?

**Comment by RitwikGupta** [comment]
We need a frontend. We have a function already defined to get the previous molecules of the week, I just need a template.
