### ISSUE TITLE
Don't crop name field

### ISSUE THREAD

**Issue by ghutchis** [pittquantum/PittQuantumRepository#44]
Some very long names get cut, e.g. http://pqr.pitt.edu/mol/BRYNGAICAJXOCY-HPRNJEQCSA-N/

Let's make sure there's a way to get the whole name, even if it's crazily long (e.g., trying to wrap into multiple lines?)

I'm open to suggestions here.

**Comment by JoshuaRogan** [comment]
For just the single molecule page or additionally in the search results? 

For the molecule page we can add it as an additional property. 

I thought the wrapping looked bad in the search results but I can figure something out if you would to have the full name in the search results.

**Comment by ghutchis** [comment]
The key thing would be in the single-molecule page. I'm not sure how to handle it in the search results, where I think it's less important.
