### ISSUE TITLE
Convert [0-9]alpha -> [0-9]α

### ISSUE THREAD

**Issue by ghutchis** [pittquantum/PittQuantumRepository#45]
For name and iupac_name fields, we should do some limited "Greek replacement"

[0-9]alpha, etc. should be converted to the appropriate Unicode entity.

I'd like to leave the JSON in ASCII for now.

**Comment by RitwikGupta** [comment]
@JoshuaRogan Can you make a filter for this?

**Comment by JoshuaRogan** [comment]
Yes, I'll get that tonight.
On Sun, Jul 12, 2015 at 3:24 AM Ritwik Gupta <notifications@github.com>
wrote:

> @JoshuaRogan <https://github.com/JoshuaRogan> Can you make a filter for
> this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pittquantum/PittQuantumRepository/issues/45#issuecomment-120698530>
> .
>
-- 
Josh Rogan
JoshuaRogan.com

**Comment by JoshuaRogan** [comment]
@ghutchis Besides alpha. What other Greek replacements. I am having a hard time finding examples in the files.

**Comment by RitwikGupta** [comment]
beta, gamma, delta

**Comment by JoshuaRogan** [comment]
They are all lower case greek letters correct?

**Comment by RitwikGupta** [comment]
Yep!

**Comment by RitwikGupta** [comment]
http://pqr.pitt.edu/mol/FPIPGXGPPPQFEQ-OVSJKPMPSA-N/

Replacements like this shouldn't occur. @ghutchis we need better rules on greek replacement.
