### ISSUE TITLE
"Links" section

### ISSUE THREAD

**Issue by ghutchis** [pittquantum/PittQuantumRepository#47]
Under both the "simple" and "detailed" view should include a redesigned section:

Links: Wikipedia | PubChem | ChemSpider

Clicking on "Links" should pop out a little "sheet" with a horizontal list of links (since we might expand this over time).

All json files should have the fields, but some will be empty (in which case the link shouldn't show):

PubChem (as existing): //pubchem.ncbi.nlm.nih.gov/compound/2519
Wikipedia - if link exists, it's the full URL, e.g. //en.wikipedia.org/wiki/Caffeine
ChemSpider: //www.chemspider.com/Chemical-Structure.2424.html

This makes it really easy for users to get to Wikipedia or PubChem when these links exist.

(I fully expect that over time, we'll have 4, 5, or more link-outs.)

**Comment by ghutchis** [comment]
This is connected to #16

**Comment by RitwikGupta** [comment]
Closing #16 because this is more descriptive
