### ISSUE TITLE
"Elements" section

### ISSUE THREAD

**Issue by ghutchis** [pittquantum/PittQuantumRepository#48]
The detailed section should include a list of elements (click-to-search):

Elements: C N H O
Elements: C N H Fe O
etc.

This is already in the JSON.

**Comment by RitwikGupta** [comment]
We should *not* add click to search on molecules. That would return 60,000 results and you do not want that.

**Comment by RitwikGupta** [comment]
Displaying them is just fine though, in my opinion.

**Comment by ghutchis** [comment]
What if I want to see all molecules with "Fe" or "Bi"? I think we just need to figure out reasonable ways to handle searching for "C" or "H" or similarly frequent elements.

I **do** want to enable click-to-search for elements... Maybe click-to-search for C, H, N, O are not enabled, but the rest are?

**Comment by RitwikGupta** [comment]
That would make the functionality really weird, if some tags were clickable and some weren't.

**Comment by ghutchis** [comment]
Agreed. So if someone clicks for "C" or "H" or some elements, maybe it just returns an error page rather than executing the search? Still, I don't think it'd take very long to return 100,000 matches considering we only show one page. It's a moderate size database, not 10,000,000 or a billion...

**Comment by RitwikGupta** [comment]
It wouldn't take long, but there would be tens of thousands of pages returned.

**Comment by JoshuaRogan** [comment]
Where in the order would you like the elements section to go?
