### ISSUE TITLE
Download Section 

### ISSUE THREAD

**Issue by ghutchis** [pittquantum/PittQuantumRepository#49]
On the "detailed" list, rather than having "Get JSON Data" we should have a pop-out sheet:

Download (click to pop-out a "sheet") with a horizontal list of downloads:

JSON Data
Mol2

This will be expanded over time with the raw QM files, e.g. "Mopac AUX" and "Mopac Output"

**Comment by JoshuaRogan** [comment]
I can easily add that once there is more stuff but I don't see a reason to have a pop out for two items.
