### ISSUE TITLE
Add DOI listings on the "simple" and "detailed" lists

### ISSUE THREAD

**Issue by ghutchis** [pittquantum/PittQuantumRepository#50]
I have not finished minting DOIs, probably not until around July 8-9th.

DOI: [10.17614/Q4P88G](//doi.org/10.17614/Q4P88G)
        [10/f28fr4](//doi.org/10/f28fr4)

The first is the DOI, the second is the shortdoi

**Comment by JoshuaRogan** [comment]
There would have to be some indication in the url to add simple or detailed. 
Ex: pqr.pitt.edu/mol/###?detailed=true
It can just be omitted for the simple view.

**Comment by ghutchis** [comment]
No, the DOI will just go to the default URL for now (i.e., simple).

I was just saying that I want the DOI entry to show up on both the "simple" and "detailed" property lists.

In principal, there's a way to do "suffix passthrough" for queries like that, but I'll have to look it up.

**Comment by ghutchis** [comment]
OK, DOI and ShortDOI are now in every JSON file and can be added to the page displays.

**Comment by ghutchis** [comment]
DOIs needed to be added to the "simple" list, but otherwise this is closed.
