### ISSUE TITLE
Add Google, Bing, etc. sitemaps

### ISSUE THREAD

**Issue by ghutchis** [pittquantum/PittQuantumRepository#52]
Adding Google, BING and other search engine sitemaps should improve indexing, e.g.

http://flask.pocoo.org/snippets/108/

**Comment by ghutchis** [comment]
When will this show up on pqr.pitt.edu? I'd like to submit to Google. Thanks.

**Comment by JoshuaRogan** [comment]
Should be up now.

**Comment by ghutchis** [comment]
Great, but what about 63000+ /mol/X pages? Thanks.

**Comment by ghutchis** [comment]
It's also not trivial, since each sitemap file can only have 50,000 locations in each. I'd suggest splitting the /mol/ URLs by first letter, e.g., all "A", etc. in separate sitemaps.

>Break up a large sitemap into a set of smaller sitemaps to prevent your server from being overloaded by serving a large file to Google. A sitemap file can't contain more than 50,000 URLs and must be no larger than 50 MB uncompressed.

>Use a sitemap index file to list all your sitemaps and submit this single file to Google rather than submitting individual sitemaps.

**Comment by JoshuaRogan** [comment]
I broke up the urls by the two letter convention we used in the folders.
