### ISSUE TITLE
"Sad face" for no match

### ISSUE THREAD

**Issue by ghutchis** [pittquantum/PittQuantumRepository#54]
We should have some sort of easter egg if there's no match for a search...

If I search for "xyzzy" I just go back to the main page.

Instead, I should get some sort of interstitial page with no match (i.e., similar to a custom 404 page):
http://chemistry.stackexchange.com/quest

**Comment by RitwikGupta** [comment]
Not sure why you're going back to the main page, but if I search for "xyzzy", or any search that doesn't exist, I get a page which says your query returned 0 results. Closing this issue.
<img width="1344" alt="screen shot 2015-07-12 at 12 09 55 am" src="https://cloud.githubusercontent.com/assets/4959141/8636827/59e48206-282a-11e5-9d19-192545dbd3c7.png">
