### ISSUE TITLE
Footer Large Screens

### ISSUE THREAD

**Issue by JoshuaRogan** [pittquantum/PittQuantumRepository#56]
The footer on very large screens isn't flush with the bottom on very large screens.

**Comment by RitwikGupta** [comment]
Do you have a screenshot of this?

**Comment by JoshuaRogan** [comment]
it should be an easy fix I will get to it. 

![screen shot 2015-08-04 at 1 02 53 pm](https://cloud.githubusercontent.com/assets/8824977/9067047/300bc552-3aa9-11e5-9545-a3baa02a1810.png)
