### ISSUE TITLE
Create "Report Issue" button

### ISSUE THREAD

**Issue by dslambrecht** [pittquantum/PittQuantumRepository#59]
so users can report broken molecules etc.

**Comment by JoshuaRogan** [comment]
This will be the URL in the footer https://github.com/pittquantum/PittQuantumRepository/issues/new?title=Missing%20Molecule%20Data%20for%20Molecule%20&body=Please%20submit%20the%20molecule%20INCHI%20Key.

**Comment by ghutchis** [comment]
Can't the footer get the InChI key automatically?

**Comment by JoshuaRogan** [comment]
It can but I believe it currently is setup as a redirect. I also would need to add a flag so it only shows up on molecule pages or after a redirect. I think if we have a flash message we can put it there.
