### ISSUE TITLE
Printer Friendly Version

### ISSUE THREAD

**Issue by JoshuaRogan** [pittquantum/PittQuantumRepository#60]
For molecules there should be an easy way to print out everything including the QR code, just the QR code, and just the data and maybe a static view of the 3D mol. 

Thoughts?

**Comment by RitwikGupta** [comment]
Yeah, there should be a printer friendly view that contains the QR code on the top right, as well as the title and molecule details on the left, and then a static view of the molecule on the center->bottom

**Comment by ghutchis** [comment]
This can potentially use #64 as well, although I don't know if people will want to set the camera "just so" before printing.
