### ISSUE TITLE
Smoother Rotation

### ISSUE THREAD

**Issue by JoshuaRogan** [pittquantum/PittQuantumRepository#61]
Rotation works perfect on desktops, modern mobile devices but sometimes isn't as smooth on slower devices. 

Reduce FPS for less powerful devices.

**Comment by ghutchis** [comment]
Is this something we can estimate or track?

**Comment by JoshuaRogan** [comment]
I played around with the settings a lot when I was working on rotation. But the problem was the pattern of browsers that wouldn't handle the rotation. Ritwik couldn't get it working smoothly on his newer laptop but my ancient laptop performed fine. It also works very fast on my iOS devices but I haven't had a chance to test it on android devices.

**Comment by RitwikGupta** [comment]
It works fine on all Android devices I've tried
