### ISSUE TITLE
Mol2 files from API link are invalid

### ISSUE THREAD

**Issue by ghutchis** [pittquantum/PittQuantumRepository#62]
The mol2 files from the API link are wrong for two reasons:

* Every line has an extra newline
* There is no file extension (.mol2) which means most programs can't recognize it

**Comment by RitwikGupta** [comment]
This is my fault. I'll fix it

**Comment by RitwikGupta** [comment]
a5d7799 was incorrect due to the mimetype. a7cc659 fixes it for good.
