### ISSUE TITLE
Use SVG preview images for search results

### ISSUE THREAD

**Issue by ghutchis** [pittquantum/PittQuantumRepository#64]
Open Babel can now generate SVG previews of the molecules, so we can switch the search results to use these:

* No worries about zoom level changing
* Can switch back to an infinite page scroll
* No need for WebGL (i.e., slow computers)

**Comment by RitwikGupta** [comment]
@JoshuaRogan this seems easy to do, want to take care of it?

**Comment by ghutchis** [comment]
I need to upload the SVG files. I'll do that tomorrow (Friday).

**Comment by RitwikGupta** [comment]
Closed with 4a2a2e0b9358ede02c843e0e503c485a22a6132d
