### ISSUE TITLE
Search results should have different UI for browse

### ISSUE THREAD

**Issue by ghutchis** [pittquantum/PittQuantumRepository#65]
I'd really like the query to be passed directly into the form value, e.g.

<img width="902" alt="screen shot 2015-07-23 at 10 43 57 pm" src="https://cloud.githubusercontent.com/assets/41128/8866644/d673f066-318c-11e5-8bb8-1f426566e893.png">

This makes it easy to edit the query and matches with common search UI (e.g., Google, Bing, etc.)

**Comment by RitwikGupta** [comment]
Moving the query to one line would be ugly, but leaving the query in the box is smart

**Comment by ghutchis** [comment]
Why would it be ugly? It would take up less space than "Search Successful Number of Pages.." in the current UI. It would probably need to flow to 2 lines on phones, but on desktop, there's clearly room IMHO.

**Comment by RitwikGupta** [comment]
It just seems very unintuitive

**Comment by ghutchis** [comment]
Heck, dump the "search results" bit, since it should be obvious from the page itself (and the user action) that it's search results:

<img width="795" alt="screen shot 2015-07-23 at 10 54 19 pm" src="https://cloud.githubusercontent.com/assets/41128/8866735/cdc0e93c-318d-11e5-8b31-3bace05b36ed.png">

<img width="778" alt="screen shot 2015-07-23 at 10 55 35 pm" src="https://cloud.githubusercontent.com/assets/41128/8866748/f81675bc-318d-11e5-84c0-63c7675d770c.png">
