### ISSUE TITLE
Generate QR codes from short DOIs

### ISSUE THREAD

**Issue by ghutchis** [pittquantum/PittQuantumRepository#66]
The JSON files should now have both DOIs and ShortDOIs, both should be shorter than the full PQR URL, e.g.

http://pqr.pitt.edu/mol/WQZGKKKJIJFFOK-GASJEMHNSA-N
http://doi.org/10.17614/Q4Z893F9R
http://doi.org/10/f3frsh

The smaller URLs will give better QR codes.

**Comment by RitwikGupta** [comment]
New JSON files are on prod

**Comment by RitwikGupta** [comment]
We don't have the ShortDOIs on the page yet, reopening.

**Comment by ghutchis** [comment]
They are in the json files, promise.

**Comment by RitwikGupta** [comment]
Yeah, we have to add them to the template is all.

**Comment by ghutchis** [comment]
I'm less concerned with putting them in the template than using them for the QR codes.

**Comment by RitwikGupta** [comment]
Oh, we can do that, no problem. Will do that sometime this week.
