### ISSUE TITLE
Fix JS minify, gzip compression

### ISSUE THREAD

**Issue by ghutchis** [pittquantum/PittQuantumRepository#70]
Google PageSpeed (and others) indicate the JS is not gzipped anymore:

![screen shot 2015-08-26 at 4 01 50 pm](https://cloud.githubusercontent.com/assets/41128/9504818/a92fb2c6-4c0c-11e5-935f-0ad318c51336.png)

**Comment by JoshuaRogan** [comment]
That's my fault I forgot to run the prod task before I pushed up the code. Will fix it tonight.

**Comment by ghutchis** [comment]
Should we make that a Git commit hook?

**Comment by JoshuaRogan** [comment]
I'll look into it but it requires that everything in package.json is installed and you have grunt installed on your machine.

**Comment by JoshuaRogan** [comment]
Had to add a type of `application/javascript` to ngnix config. Only had `application/x-javascript`. Closes #70
