### ISSUE TITLE
Add "Recenter" button

### ISSUE THREAD

**Issue by ghutchis** [pittquantum/PittQuantumRepository#81]
Sometimes the zooming/rotating gets things mixed up.

There should be a "Recenter" button:

<input type="button" value="Recenter" onclick="glviewer.zoomTo();"></input>

**Comment by RitwikGupta** [comment]
There already is a reset zoom button. It's the middle one.

<img width="110" alt="capture3" src="https://cloud.githubusercontent.com/assets/4959141/12974099/45779288-d07f-11e5-9848-16a76a5b9f7f.PNG">
