### ISSUE TITLE
Article Listing needs Formatting

### ISSUE THREAD

**Issue by ghutchis** [pittquantum/PittQuantumRepository#84]
The "News" article listing needs formatting. It should read something like:

- Dec. 12, 2015 - Using PQR in Course Materials
- Aug. 11, 2015 - Frequently Asked Questions

Not..
<img width="426" alt="screen shot 2016-02-10 at 9 10 47 pm" src="https://cloud.githubusercontent.com/assets/41128/12968045/d2b6a2f0-d03a-11e5-98b1-4c89434cce71.png">

**Comment by ghutchis** [comment]
I don't know if the best solution is a cache or a summary index file, etc.

But the formatting looks ugly right now.

**Comment by RitwikGupta** [comment]
Closed with 074d7e3

**Comment by RitwikGupta** [comment]
<img width="426" alt="capture3" src="https://cloud.githubusercontent.com/assets/4959141/13167726/dba4b928-d6a3-11e5-8fd9-e75ce6e6ba43.PNG">
