### ISSUE TITLE
Prevent "bad gateway error?"

### ISSUE THREAD

**Issue by ghutchis** [pittquantum/PittQuantumRepository#89]
Can we redirect to the main page or the search interface rather than the "bad gateway" error?

e.g.
https://pqr.pitt.edu/mol/ULG

**Comment by RitwikGupta** [comment]
Closed with 9b3ec55352546ed23f73b77fe68512071db5cb2b

**Comment by RitwikGupta** [comment]
Nginx causes a redirect now
