### ISSUE TITLE
Add thin black outline?

### ISSUE THREAD

**Issue by ghutchis** [pittquantum/PittQuantumRepository#90]
Can we add a thin black outline to improve image quality?

viewer.setViewStyle({style:"outline",color:"black", width:0.1});

See the 3DMol.js poster from the ACS meeting:
http://bits.csb.pitt.edu/files/3Dmol_ACS2016.pdf

**Comment by RitwikGupta** [comment]
Is this what you're looking for?
![one](http://i.imgur.com/tzfBYLx.png)
![two](http://i.imgur.com/GEa3Yfb.png)

**Comment by ghutchis** [comment]
Something like that, but perhaps thinner (e.g., 1/3 the thickness)? I'm wondering if it's possible to basically add a thin black trace. If that was 0.1, maybe 0.03 or something.

And perhaps we should only do it for the surface - the molecule itself looks pretty good without it.

I'm just thinking this will help with the white-on-white look between the molecule surface and the site background.

**Comment by RitwikGupta** [comment]
I think that with 0.01 outline width, the outline looks great on both the surface and molecule! Thoughts?
![0.01](http://i.imgur.com/o2sUQyp.png)
![0.01](http://i.imgur.com/dnU0mvi.png)

**Comment by ghutchis** [comment]
Yes, looks great.

**Comment by RitwikGupta** [comment]
Closing with 646676ad1341f3c8da1928d394c511646af86754
